[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "df-gen"
version = "0.1.0"
description = "Flexible synthetic DataFrame generator"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Sarah Dippolito" }
]
dependencies = [
    "numpy",
    "pandas",
    "string",
    "random"
]

[project.urls]
Homepage = "https://github.com/sarah-dippolito/df_gen"
Repository = "https://github.com/sarah-dippolito/df_gen.git"
